name:                datagram
version:             0.1.0.0
github:              "Yannissss/datagram"
license:             BSD3
author:              "Yannissss"
maintainer:          "yannissss@nowhere.fr"
copyright:           "2020 Yannissss"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:           Monadic UDP Datagram interface for Haskell 

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

tests:
  datagram-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - datagram
